export const MENU_STRUCTURE = {
    Dashboard: [
        'Accessibility',
        'Animation',
        'App',
        'Content',
        'Graphics',
        'Media',
        'NFC',
        'OS',
        'Preference',
        'Text',
        'Views',
    ],

    Views: [
        'Animation',
        'Auto Complete',
        'Buttons',
        'Chronometer',
        'Controls',
        'Custom',
        'Date Widgets',
        'Drag and Drop',
        'Expandable Lists',
        'Focus',
        'Gallery',
        'Game Controller Input',
        'Grid',
        'Hover Events',
        'Image Button',
        'Image Switcher',
        'Layout Animation',
        'Lists',
        'Menu',
        'Picker',
        'Popup Menu',
        'Progress Bar',
        'Radio Group',
        'Rating Bar',
        'Scroll Bars',
        'Search View',
        'Seek Bar',
        'Spinner',
        'Switches',
        'Tabs',
        'Text Clock',
        'Text Fields',
        'Text Switcher',
        'Visibility',
        'WebView',
    ],

    NFC: [
        'ForegroundDispatch',
        'ForegroundNdefPush',
        'TechFilter',
    ],

    App: [
        'Activity',
        'Alert Dialogs',
        'Fragment',
        'Notification',
        'Search',
        'Service',
        'Voice Recognition',
    ],

    Preference: [
        'Default values',
        'Dependencies',
        'From XML',
        'Headers',
        'Switch',
    ],
};
